version: 2

sources: 
  - name: snowflake_sample_data_tpcds_sf10tcl
    database: snowflake_sample_data
    schema: TPCDS_SF10TCL
    tables:
      - name: STORE_SALES
        columns:
        - name: ss_item_sk
        description: primary key of the store sales table
        tests :
          - not_null
          - unique
              
      - name: STORE_RETURNS

  - name: snowflake_sample_data_tpch_sf1
    database: snowflake_sample_data
    schema: tpch_sf1
    tables:
      - name: customer
  
  - name: fivetran_database_dbt_default_schema
    database: fivetran_database
    schema: dbt_default_schema
    tables:
      - name: CLEANSED_PRESCRIPTION_PRACTISE
        columns:
           - name: AGE
             tests: 
               - is_even
               - not_null

      - name: CLEANSED_PRODUCT_PRACTISE
        columns:
           - name: PRODUCT_ID
             tests: 
               - not_null


models:
  - name: Custom_schema_test_Prescription_Age
    columns:
      - name: AGE
        tests:
          - is_even
