with product as (
    select * from FIVETRAN_DATABASE.RAW.PRODUCT
)

select PRODUCT_ID,
trim(PRODUCT_NAME) PRODUCT_NAME,
trim(THERAPEUTIC_AREA) THERAPEUTIC_AREA,
trim(COMPANY) COMPANY,
BRAND_TYPE,
DOSAGE_FORM,
LAUNCH_DATE,
from product